### ISSUE TITLE
Database-Design

### ISSUE THREAD

**Issue by C4L86** [C4L86/02-29-pair-project#2]
https://docs.google.com/spreadsheets/d/1DLBjrKgJ3UMHzHGuj6o-xG6_fo5fPOkETbm0EuBXHrE/edit#gid=490267076

**Comment by halfghaninne** [comment]
I just requested permission to view!

**Comment by C4L86** [comment]
https://docs.google.com/spreadsheets/d/1DLBjrKgJ3UMHzHGuj6o-xG6_fo5fPOkETbm0EuBXHrE/edit?usp=sharing

**Comment by halfghaninne** [comment]
In users:
- Please change name of `first name` and `last name` columns to include underscores. 
- What is rank?

**Comment by halfghaninne** [comment]
In games:
- What is `immersion level`? Does it refer to categories defined in some other table?
- Is price something that will be standardized?
- `logged run time`, `user rating`, `number of plays`, and `winner` don't seem to belong here. Seems like this will be different for each user who plays.

**Comment by C4L86** [comment]
Should we create a third table for individual plays of a single game?

**Comment by santaclauslives** [comment]
Immersion level is maybe not the best term. Trying to say if it is casual and you are just yourself,  or more of a role-play game where you take on an identity and you have to learn about your character.

**Comment by halfghaninne** [comment]
So what is the data type of `immersion level`?

I think another table for plays makes sense!

**Comment by santaclauslives** [comment]
It looks like there have been stabs at difficulty ratings or that sort of thing on board game geek and whatnot, but nothing is sticking, so we may cut that category. At most it might be a boolean of role-play yes or no.
